# Site settings
title: Light- Blog
SEOTitle: Light- 的小站
header-img: images/yy_title.JPG
email: zhoubohan.pro@gmail.com
description: "想成为一束光。"
keyword: "Light- Blog, Light-的小站"
url: "https://zbh0323.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zbh0323/zbh0323.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "stay gold, stay hungry"
sidebar-avatar: /img/yeswecode.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
github_username:    zbh0323





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 13
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate,jemoji,jekyll-sitemap]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Gitalk
gitalk:
  enable: true   #是否开启Gitalk评论
  clientID: 391bb50bacb8e159a83d        # 嘿，别乱看我的秘密                #生成的clientID
  clientSecret: a69935bca2f94e355b1786d6be5b94e7b7b882c3    #生成的clientSecret
  repo: zbh0323.github.io    #仓库名称
  owner: zbh0323    #github用户名
  admin: zbh0323
  distractionFreeMode: false #是否启用类似FB的阴影遮罩
  perPage: 15


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 8781537abaedfc88ee226419437972a7
ga_track_id: 'G-RXVXV4EG4Z'
ga_domain: auto






# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1             # 相同标签数量大于这个数，才会出现在首页


# Friends
friends: [
    {
        title: "七夏浅笑",
        href: "http://julydate.com/"
    },{
        title: "草地上的蚂蚁的博客",
        href: "https://hillychen.github.io/"
    },{
        title: "Jiyiren.Blog",
        href: "https://jiyiren.github.io/"
    },{
        title: "由我管理的NoSchoolBlog",
        href: "https://kalicn.github.io/noschoolblog/"
    },{
        title: "Tianhaoo的博客",
        href: "https://tianhaoo.github.io/"
    }    
]
